version: "3"
services:
  postgresql:
    restart: always
    image: postgres
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  app:
    build: .
    depends_on:
      - postgresql
    ports:
      - "${PORT}:${PORT}"
    command: npm run start
